# Generated by Django 5.2.1 on 2025-06-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(default='Не указан', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Опыт работы в годах', null=True, verbose_name='Стаж работы'),
        ),
    ]
