# Generated by Django 5.2.1 on 2025-06-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_master_address_alter_master_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_approved', 'Новая'), ('approved', 'Подтверждена'), ('in_progress', 'В процессе'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='not_approved', max_length=50, verbose_name='Статус заявки'),
        ),
    ]
