# Generated by Django 5.2.1 on 2025-06-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_master_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Опыт работы в годах', verbose_name='Стаж работы'),
        ),
    ]
