# Generated by Django 5.2.1 on 2025-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review_ai_checked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(choices=[('ai_checked_true', 'Одобрено ИИ'), ('ai_cancelled', 'Не прошло модерацию'), ('ai_checked_in_progress', 'В процессе проверки'), ('ai_checked_false', 'Не проверено')], default='ai_checked_false', max_length=30, verbose_name='Статус ИИ'),
        ),
    ]
