# Generated by Django 5.2.1 on 2025-07-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_review_ai_checked_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тег для уведомлений'),
        ),
    ]
